set number
set hlsearch
set ignorecase
set clipboard+=unnamed

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

command! Test :w | :!python -m unittest discover

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" ### Vim-Plug ### start
"
" Installation, if not already there 
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugin list
call plug#begin()

Plug 'rust-lang/rust.vim'

Plug 'itchyny/lightline.vim'
set laststatus=2
set noshowmode

Plug 'preservim/nerdtree'
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

Plug 'preservim/nerdcommenter'

call plug#end()

" ### Vim-Plug ### end

" Solarized options
syntax enable
set background=dark
colorscheme solarized
